services:
  - name: flask-server
    type: web
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: python flask_server.py
    envVars:
      - key: GOOGLE_API_KEY
        sync: false  
    autoDeploy: true
    region: oregon  
